// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace AppEmployee.Dll.Entities
{
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_LastName { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_Zip { get; set; }
        public DateTime? Emp_HireDate { get; set; }
    }
}